// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOV9nScAzGRVUPOWTk6P6BAmCmq4k4-Wo',
    appId: '1:1010467027551:web:2f395e57f5ec27089e79ea',
    messagingSenderId: '1010467027551',
    projectId: 'resto-task',
    authDomain: 'resto-task.firebaseapp.com',
    storageBucket: 'resto-task.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkQvQfA8YQDXY8n7zMFU6EEWDMgaa5KWk',
    appId: '1:1010467027551:android:5c98ce4c3a6a13279e79ea',
    messagingSenderId: '1010467027551',
    projectId: 'resto-task',
    storageBucket: 'resto-task.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYaFBsXuF8klnvwE8z3x_jn-JZOQH2IDk',
    appId: '1:1010467027551:ios:17c4bd2d8a3de60e9e79ea',
    messagingSenderId: '1010467027551',
    projectId: 'resto-task',
    storageBucket: 'resto-task.appspot.com',
    iosClientId: '1010467027551-81gfvd9n8bu7rd06tfemvmhcp182c4kq.apps.googleusercontent.com',
    iosBundleId: 'com.example.orderingSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYaFBsXuF8klnvwE8z3x_jn-JZOQH2IDk',
    appId: '1:1010467027551:ios:17c4bd2d8a3de60e9e79ea',
    messagingSenderId: '1010467027551',
    projectId: 'resto-task',
    storageBucket: 'resto-task.appspot.com',
    iosClientId: '1010467027551-81gfvd9n8bu7rd06tfemvmhcp182c4kq.apps.googleusercontent.com',
    iosBundleId: 'com.example.orderingSystem',
  );
}
